### ISSUE TITLE
Do not move tickets in Jira backwards

### ISSUE THREAD

**Issue by git-decadent** [zattoo/issuer#7]
I would like to suggest that only those tickets which are in Jira have "In Development" status should be moved by issues to "In Review". 
I accidentally found an issue when my ticket was moved from "Ready to QA" back to "In Review" because I did a typo in the title. I guess this might happen to tickets that already have statuses like "Ready for Release" or "Done", which can cause a mess in Jira.

**Comment by nitzanashi** [comment]
@git-decadent sounds like it's related to the integration with JIRA, which is not being covered by the action. I think it's something that can be solved in the JIRA settings of the project, since in WEB we don't see that issue

**Comment by gotbahn** [comment]
The issue is not related to issuer action. It doesn't communicate with JIRA API.
